const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),scoreEl=$('score'),livesEl=$('lives'),timerEl=$('timer'),powerEl=$('power'),startBtn=$('startBtn'),settingsBtn=$('settingsBtn'),settingsMenu=$('settingsMenu'),gameOverMenu=$('gameOverMenu'),scoreboardMenu=$('scoreboardMenu'),finalScore=$('finalScore'),playerName=$('playerName'),saveScoreBtn=$('saveScoreBtn'),saveScoreBox=$('saveScoreBox'),scoreList=$('scoreList');
const pauseOverlay=$('pauseOverlay');
let width,height,cx,cy,scale=1,player,enemies,bullets,enemyBullets,particles,powerups,score=0,lives=3,running=false,paused=false,startTime,timerId,lastFire=0,targetX,targetY,power=0,slowUntil=0,invulnerableUntil=0,deferredPrompt=null;
const powerTable=Array.from({length:50},(_,i)=>({shots:1,cooldown:Math.max(42,126-i*1.7),speed:13+i*.12,spread:Math.min(.48,.09+i*.008),side:i>=2,wide:i>=7,heavy:i>=10,rapid:i>=16,back:i>=20,quad:i>=30}));
function resize(){width=innerWidth;height=innerHeight;canvas.width=width;canvas.height=height;cx=width/2;cy=height/2;scale=Math.max(.78,Math.min(1.18,Math.min(width,height)/390))}addEventListener('resize',resize);resize();const S=n=>n*scale;
function secs(){return running?Math.floor((Date.now()-startTime)/1000):0}function tier(){return Math.floor(secs()/20)}function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push(new Particle(x,y,c))}function overlap(a,b){const x=a.x-b.x,y=a.y-b.y;return x*x+y*y<(a.r+b.r)*(a.r+b.r)}
class Player{constructor(){this.x=cx;this.y=height*.8;this.size=S(16)}update(x,y){this.size=S(16);if(x!==undefined){this.x=x;this.y=y}this.x=Math.max(this.size,Math.min(width-this.size,this.x));this.y=Math.max(this.size,Math.min(height-this.size,this.y))}draw(){const flash=Date.now()<invulnerableUntil&&Math.floor(Date.now()/70)%2===0;ctx.save();ctx.translate(this.x,this.y);ctx.beginPath();ctx.moveTo(0,-this.size);ctx.lineTo(-this.size*.72,this.size*.72);ctx.lineTo(this.size*.72,this.size*.72);ctx.closePath();ctx.strokeStyle=flash?'#ff3d3d':'#fff';ctx.lineWidth=S(2.5);ctx.stroke();ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size*.68}}}
class Enemy{constructor(kind='basic'){this.kind=kind;const edge=Math.floor(Math.random()*3);if(edge===0){this.x=Math.random()*width;this.y=-S(32)}else if(edge===1){this.x=width+S(32);this.y=Math.random()*height*.7}else{this.x=-S(32);this.y=Math.random()*height*.7}const a=Math.atan2(height*.58-this.y,cx-this.x),mult=1+tier()*.1;this.vx=Math.cos(a)*S((1.22+Math.random()*1.05)*mult);this.vy=Math.sin(a)*S((1.22+Math.random()*1.05)*mult);this.size=S(kind==='armored'?19:12+Math.random()*9);this.rot=0;this.lastShot=Date.now()+Math.random()*1000;this.hp=kind==='armored'?Math.min(8,3+Math.floor(power/10)):1;this.hitUntil=0}update(factor){this.x+=this.vx*factor;this.y+=this.vy*factor;this.rot+=.04*factor;if(this.kind==='shooter'&&Date.now()-this.lastShot>Math.max(330,1200-tier()*34)){enemyBullets.push(new EnemyBullet(this.x,this.y+this.size*.8));this.lastShot=Date.now()}}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rot);ctx.strokeStyle=Date.now()<this.hitUntil&&Math.floor(Date.now()/70)%2===0?'#fff':this.kind==='shooter'?'#ff963d':this.kind==='armored'?'#bd4aff':'#ff4444';ctx.lineWidth=S(2);ctx.beginPath();ctx.arc(0,0,this.size,0,Math.PI*2);ctx.stroke();if(this.kind==='shooter'){ctx.beginPath();ctx.moveTo(0,-this.size*.42);ctx.lineTo(0,this.size*.42);ctx.stroke()}if(this.kind==='armored'){ctx.beginPath();ctx.arc(0,0,this.size*.55,0,Math.PI*2);ctx.stroke()}ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size}}}
class Powerup{constructor(){this.x=S(28)+Math.random()*(width-S(56));this.y=-S(28);this.size=S(18);this.vy=S(2+tier()*.09);this.rot=0}update(f){this.y+=this.vy*f;this.rot+=.03*f}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rot);ctx.strokeStyle='#249bff';ctx.lineWidth=S(3);ctx.strokeRect(-this.size/2,-this.size/2,this.size,this.size);ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size*.72}}}
class Bullet{constructor(x,y,vx=0,vy=-1,damage=1){this.x=x;this.y=y;this.vx=vx;this.vy=vy<0?-S(powerTable[power].speed):S(powerTable[power].speed);this.r=S(damage>1?4.6:3.4);this.life=125;this.damage=damage}update(f){this.x+=this.vx*f;this.y+=this.vy*f;this.life--}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}b(){return{x:this.x,y:this.y,r:this.r}}}
class EnemyBullet{constructor(x,y){this.x=x;this.y=y;this.vy=S(5.8+tier()*.16);this.r=S(4);this.life=190}update(f){this.y+=this.vy*f;this.life--}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle='#ff783d';ctx.fill()}b(){return{x:this.x,y:this.y,r:this.r}}}
class Particle{constructor(x,y,c){this.x=x;this.y=y;const a=Math.random()*Math.PI*2,s=S(Math.random()*3.5);this.vx=Math.cos(a)*s;this.vy=Math.sin(a)*s;this.life=1;this.d=.025+Math.random()*.03;this.c=c;this.r=S(1.5+Math.random()*2.5)}update(f){this.x+=this.vx*f;this.y+=this.vy*f;this.life-=this.d*f}draw(){ctx.globalAlpha=Math.max(0,this.life);ctx.fillStyle=this.c;ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
function chooseEnemy(){const t=tier(),r=Math.random();if(t>=4&&r<Math.min(.14+t*.018,.42))return'armored';if(t>=2&&r<Math.min(.2+t*.018,.52))return'shooter';return'basic'}function spawn(){const t=tier(),cap=8+t*3,rate=.032+t*.006;if(enemies.length<cap&&Math.random()<rate)enemies.push(new Enemy(chooseEnemy()));if(Math.random()<.0017+Math.min(t,16)*.00025)powerups.push(new Powerup())}
function addShot(x,y,vx,vy,damage){bullets.push(new Bullet(x,y,vx,vy,damage))}function shoot(now){const p=powerTable[power];if(now-lastFire<p.cooldown)return;lastFire=now;const damage=1+Math.floor(power/8);addShot(player.x,player.y-player.size,0,-1,damage);if(p.side){addShot(player.x,player.y,-S(p.speed),0,damage);addShot(player.x,player.y,S(p.speed),0,damage)}if(p.back){addShot(player.x,player.y,0,1,damage)}if(p.wide){addShot(player.x,player.y-player.size,-S(4.4),-1,damage);addShot(player.x,player.y-player.size,S(4.4),-1,damage)}if(p.quad){addShot(player.x,player.y,-S(4.4),-1,damage);addShot(player.x,player.y,S(4.4),-1,damage)}}
function damage(){if(Date.now()<invulnerableUntil)return;lives--;livesEl.textContent='Lives: '+lives;invulnerableUntil=Date.now()+850;slowUntil=Date.now()+500;burst(player.x,player.y,'#ff3d3d',18);if(lives<=0)gameOver()}
function collisions(){const pb=player.b();for(let i=powerups.length-1;i>=0;i--){for(let j=bullets.length-1;j>=0;j--){if(overlap(powerups[i].b(),bullets[j].b())){const p=powerups[i];powerups.splice(i,1);bullets.splice(j,1);power=Math.min(49,power+1);powerEl.textContent='Power: '+power;score+=250;scoreEl.textContent='Score: '+score;burst(p.x,p.y,'#249bff',18);break}}}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],eb=e.b();if(overlap(pb,eb)){enemies.splice(i,1);burst(e.x,e.y,'#ff4444',14);damage();continue}for(let j=bullets.length-1;j>=0;j--){if(overlap(eb,bullets[j].b())){bullets.splice(j,1);e.hp--;e.hitUntil=Date.now()+180;if(e.hp<=0){enemies.splice(i,1);score+=e.kind==='armored'?250:100;scoreEl.textContent='Score: '+score;burst(e.x,e.y,e.kind==='armored'?'#bd4aff':'#ff4444',16)}break}}}for(let i=enemyBullets.length-1;i>=0;i--){if(overlap(pb,enemyBullets[i].b())){enemyBullets.splice(i,1);damage()}}}
function updateTimer(){const t=secs();timerEl.textContent='Time: '+Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}
function update(){if(paused)return;const f=Date.now()<slowUntil?.32:1;player.update(targetX,targetY);const now=Date.now();shoot(now);enemies.forEach(x=>x.update(f));powerups.forEach(x=>x.update(f));bullets.forEach(x=>x.update(f));enemyBullets.forEach(x=>x.update(f));particles.forEach(x=>x.update(f));enemies=enemies.filter(x=>x.x>-S(100)&&x.x<width+S(100)&&x.y>-S(100)&&x.y<height+S(100));powerups=powerups.filter(x=>x.y<height+S(50));bullets=bullets.filter(x=>x.life>0&&x.y>-S(40)&&x.y<height+S(40));enemyBullets=enemyBullets.filter(x=>x.life>0&&x.y<height+S(40));particles=particles.filter(x=>x.life>0);spawn();collisions()}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);player.draw();enemies.forEach(x=>x.draw());powerups.forEach(x=>x.draw());bullets.forEach(x=>x.draw());enemyBullets.forEach(x=>x.draw());particles.forEach(x=>x.draw())}
function loop(){if(!running)return;update();draw();requestAnimationFrame(loop)}
function resetGame(){player=new Player();enemies=[];bullets=[];enemyBullets=[];particles=[];powerups=[];score=0;lives=3;power=0;targetX=undefined;targetY=undefined;slowUntil=0;invulnerableUntil=0;scoreEl.textContent='Score: 0';livesEl.textContent='Lives: 3';powerEl.textContent='Power: 0'}function startGame(){resetGame();running=true;paused=false;startTime=Date.now();lastFire=0;clearInterval(timerId);timerId=setInterval(updateTimer,1000);updateTimer();startBtn.style.display='none';settingsBtn.style.display='block';settingsMenu.classList.add('hidden');gameOverMenu.classList.add('hidden');scoreboardMenu.classList.add('hidden');pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}
function pauseGame(){paused=true;pauseOverlay.classList.remove('hidden');settingsMenu.classList.add('hidden')}function resumeGame(){paused=false;pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}function gameOver(){running=false;clearInterval(timerId);power=0;powerEl.textContent='Power: 0';finalScore.textContent='Score: '+score+' · Time: '+timerEl.textContent.replace('Time: ','');playerName.value='';saveScoreBox.classList.remove('hidden');gameOverMenu.classList.remove('hidden');settingsBtn.style.display='none'}
function scores(){try{return JSON.parse(localStorage.getItem('infinityScores')||'[]')}catch{return[]}}function renderScores(){const all=scores();scoreList.innerHTML=all.length?all.map(x=>'<li>'+escapeHtml(x.name)+' <span class="score-value">'+x.score+'</span></li>').join(''):'<li>Nessun punteggio salvato</li>'}function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function saveScore(){const name=(playerName.value.trim()||'Player').slice(0,14),all=scores();all.push({name,score,time:secs(),date:Date.now()});all.sort((a,b)=>b.score-a.score||b.time-a.time);localStorage.setItem('infinityScores',JSON.stringify(all.slice(0,10)));saveScoreBox.classList.add('hidden');renderScores()}
function forceRefresh(){if('caches'in window)caches.keys().then(k=>Promise.all(k.map(x=>caches.delete(x))).then(()=>location.replace(location.pathname+'?update='+Date.now())));else location.replace(location.pathname+'?update='+Date.now())}
function setTarget(e){targetX=e.clientX;targetY=e.clientY}canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('touchstart',e=>e.preventDefault(),{passive:false});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
settingsBtn.onclick=()=>{settingsMenu.classList.remove('hidden');$('pauseBtn').classList.toggle('hidden',paused);$('resumeBtn').classList.toggle('hidden',!paused)};$('newGameBtn').onclick=startGame;$('pauseBtn').onclick=pauseGame;$('resumeBtn').onclick=()=>{settingsMenu.classList.add('hidden');resumeGame()};$('restartBtn').onclick=startGame;$('scoresBtn').onclick=()=>{settingsMenu.classList.add('hidden');renderScores();scoreboardMenu.classList.remove('hidden')};$('closeSettingsBtn').onclick=()=>settingsMenu.classList.add('hidden');$('restartFromGameOverBtn').onclick=startGame;$('showScoresFromGameOverBtn').onclick=()=>{gameOverMenu.classList.add('hidden');renderScores();scoreboardMenu.classList.remove('hidden')};$('closeScoresBtn').onclick=()=>scoreboardMenu.classList.add('hidden');saveScoreBtn.onclick=saveScore;$('refreshBtn').onclick=forceRefresh;$('resumeFromPauseBtn').onclick=resumeGame;$('restartFromPauseBtn').onclick=startGame;$('iosInstallBtn').onclick=()=>{settingsMenu.classList.add('hidden');$('iosInstallHelp').classList.remove('hidden')};$('closeIosInstallHelpBtn').onclick=()=>$('iosInstallHelp').classList.add('hidden');startBtn.onclick=startGame;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);
const backToSettings=()=>{scoreboardMenu.classList.add('hidden');gameOverMenu.classList.remove('hidden')};$('restartFromScoreboardBtn').onclick=startGame;$('backFromScoreboardBtn').onclick=backToSettings;$('backFromPauseBtn').onclick=()=>{pauseOverlay.classList.add('hidden');settingsMenu.classList.remove('hidden')};