const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),livesEl=document.getElementById('lives'),timerEl=document.getElementById('timer'),powerEl=document.getElementById('power');
const startBtn=document.getElementById('startBtn'),settingsBtn=document.getElementById('settingsBtn'),settingsMenu=document.getElementById('settingsMenu'),newGameBtn=document.getElementById('newGameBtn'),pauseBtn=document.getElementById('pauseBtn'),resumeBtn=document.getElementById('resumeBtn'),restartBtn=document.getElementById('restartBtn'),refreshBtn=document.getElementById('refreshBtn'),installBtn=document.getElementById('installBtn'),closeSettingsBtn=document.getElementById('closeSettingsBtn'),pauseOverlay=document.getElementById('pauseOverlay'),resumeFromPauseBtn=document.getElementById('resumeFromPauseBtn'),restartFromPauseBtn=document.getElementById('restartFromPauseBtn');
let width,height,centerX,centerY,player,enemies,bullets,particles,powerups,score,lives,gameRunning=false,paused=false,lastTime,startTime,timerInterval,lastFireTime=0,playerTargetX,playerTargetY,firePower=1,deferredInstallPrompt=null;
function resize(){width=innerWidth;height=innerHeight;canvas.width=width;canvas.height=height;centerX=width/2;centerY=height/2}addEventListener('resize',resize);resize();
class Player{constructor(){this.x=centerX;this.y=height*.8;this.size=16}update(x,y){if(x!==undefined){this.x=x;this.y=y}this.x=Math.max(this.size,Math.min(width-this.size,this.x));this.y=Math.max(this.size,Math.min(height-this.size,this.y))}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.beginPath();ctx.moveTo(0,-this.size);ctx.lineTo(-this.size*.72,this.size*.72);ctx.lineTo(this.size*.72,this.size*.72);ctx.closePath();ctx.strokeStyle='#fff';ctx.lineWidth=2.5;ctx.stroke();ctx.restore()}bounds(){return{x:this.x,y:this.y,r:this.size*.68}}}
class Enemy{constructor(){const edge=Math.floor(Math.random()*4);if(edge===0){this.x=Math.random()*width;this.y=-30}else if(edge===1){this.x=width+30;this.y=Math.random()*height}else if(edge===2){this.x=Math.random()*width;this.y=height+30}else{this.x=-30;this.y=Math.random()*height}const level=difficulty();const a=Math.atan2(centerY-this.y,centerX-this.x),speed=(1+Math.random()*1.4)*(1+level*.16);this.vx=Math.cos(a)*speed;this.vy=Math.sin(a)*speed;this.size=12+Math.random()*11;this.rotation=0;this.rotationSpeed=(Math.random()-.5)*.06}update(){this.x+=this.vx;this.y+=this.vy;this.rotation+=this.rotationSpeed}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rotation);ctx.beginPath();ctx.arc(0,0,this.size,0,Math.PI*2);ctx.strokeStyle='#ff4444';ctx.lineWidth=2;ctx.stroke();ctx.restore()}bounds(){return{x:this.x,y:this.y,r:this.size}}}
class Powerup{constructor(){this.x=28+Math.random()*(width-56);this.y=-28;this.size=18;this.vy=1.5+difficulty()*.18;this.rotation=0}update(){this.y+=this.vy;this.rotation+=.03}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rotation);ctx.strokeStyle='#249bff';ctx.lineWidth=3;ctx.strokeRect(-this.size/2,-this.size/2,this.size,this.size);ctx.restore()}bounds(){return{x:this.x,y:this.y,r:this.size*.75}}}
class Bullet{constructor(x,y,vx=0){this.x=x;this.y=y;this.vx=vx;this.vy=-13;this.r=3.5;this.life=110}update(){this.x+=this.vx;this.y+=this.vy;this.life--}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}bounds(){return{x:this.x,y:this.y,r:this.r}}}
class Particle{constructor(x,y,color){this.x=x;this.y=y;const a=Math.random()*Math.PI*2,s=Math.random()*3.5;this.vx=Math.cos(a)*s;this.vy=Math.sin(a)*s;this.life=1;this.decay=.025+Math.random()*.03;this.color=color;this.r=1.5+Math.random()*2.5}update(){this.x+=this.vx;this.y+=this.vy;this.life-=this.decay}draw(){ctx.globalAlpha=Math.max(0,this.life);ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
function elapsed(){return gameRunning?Math.floor((Date.now()-startTime)/1000):0}function difficulty(){return Math.floor(elapsed()/15)}function circles(a,b){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<(a.r+b.r)*(a.r+b.r)}function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push(new Particle(x,y,c))}
function setTarget(e){playerTargetX=e.clientX;playerTargetY=e.clientY}canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('touchstart',e=>e.preventDefault(),{passive:false});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
function spawn(){const level=difficulty(),enemyCap=10+level*2;if(enemies.length<enemyCap&&Math.random()<.028+level*.004)enemies.push(new Enemy());if(Math.random()<.0018+Math.min(level,8)*.00035)powerups.push(new Powerup())}
function shoot(now){const cooldown=Math.max(62,120-(firePower-1)*12);if(now-lastFireTime<cooldown)return;lastFireTime=now;const count=Math.min(firePower,5),spread=.16;for(let i=0;i<count;i++){const offset=(i-(count-1)/2)*spread;bullets.push(new Bullet(player.x,player.y-player.size,Math.sin(offset)*13))}}
function collisions(){const pb=player.bounds();for(let i=powerups.length-1;i>=0;i--){const p=powerups[i];for(let j=bullets.length-1;j>=0;j--){if(circles(p.bounds(),bullets[j].bounds())){powerups.splice(i,1);bullets.splice(j,1);firePower=Math.min(5,firePower+1);powerEl.textContent='Power: '+firePower;score+=250;scoreEl.textContent='Score: '+score;burst(p.x,p.y,'#249bff',18);break}}}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],eb=e.bounds();if(circles(pb,eb)){enemies.splice(i,1);lives--;livesEl.textContent='Lives: '+lives;burst(e.x,e.y,'#ff4444',14);if(lives<=0)gameOver();continue}for(let j=bullets.length-1;j>=0;j--){if(circles(eb,bullets[j].bounds())){enemies.splice(i,1);bullets.splice(j,1);score+=100;scoreEl.textContent='Score: '+score;burst(e.x,e.y,'#ff4444',12);break}}}}
function updateTimer(){const t=elapsed();timerEl.textContent='Time: '+Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}
function update(){if(paused)return;player.update(playerTargetX,playerTargetY);const now=Date.now();shoot(now);enemies.forEach(x=>x.update());powerups.forEach(x=>x.update());bullets.forEach(x=>x.update());particles.forEach(x=>x.update());enemies=enemies.filter(x=>x.x>-80&&x.x<width+80&&x.y>-80&&x.y<height+80);powerups=powerups.filter(x=>x.y<height+40);bullets=bullets.filter(x=>x.life>0&&x.y>-30);particles=particles.filter(x=>x.life>0);spawn();collisions()}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);player.draw();enemies.forEach(x=>x.draw());powerups.forEach(x=>x.draw());bullets.forEach(x=>x.draw());particles.forEach(x=>x.draw())}
function loop(t){if(!gameRunning)return;lastTime=t;update();draw();requestAnimationFrame(loop)}
function startGame(){player=new Player();enemies=[];bullets=[];particles=[];powerups=[];score=0;lives=3;firePower=1;playerTargetX=undefined;playerTargetY=undefined;scoreEl.textContent='Score: 0';livesEl.textContent='Lives: 3';powerEl.textContent='Power: 1';gameRunning=true;paused=false;startTime=Date.now();lastFireTime=0;clearInterval(timerInterval);timerInterval=setInterval(updateTimer,1000);updateTimer();startBtn.style.display='none';settingsBtn.style.display='block';settingsMenu.classList.add('hidden');pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}
function pauseGame(){paused=true;pauseOverlay.classList.remove('hidden');settingsMenu.classList.add('hidden')}function resumeGame(){paused=false;pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}function gameOver(){gameRunning=false;clearInterval(timerInterval);startBtn.textContent='Restart';startBtn.style.display='block';settingsBtn.style.display='none'}
function forceRefresh(){if('caches'in window)caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k))).then(()=>location.replace(location.pathname+'?update='+Date.now())));else location.replace(location.pathname+'?update='+Date.now())}
settingsBtn.onclick=()=>{settingsMenu.classList.remove('hidden');pauseBtn.classList.toggle('hidden',paused);resumeBtn.classList.toggle('hidden',!paused)};newGameBtn.onclick=startGame;pauseBtn.onclick=pauseGame;resumeBtn.onclick=()=>{settingsMenu.classList.add('hidden');resumeGame()};restartBtn.onclick=startGame;refreshBtn.onclick=forceRefresh;closeSettingsBtn.onclick=()=>settingsMenu.classList.add('hidden');resumeFromPauseBtn.onclick=resumeGame;restartFromPauseBtn.onclick=startGame;startBtn.onclick=startGame;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.classList.add('hidden')};window.addEventListener('appinstalled',()=>installBtn.classList.add('hidden'));
ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);
