const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);const scoreEl=$('score'),livesEl=$('lives'),timerEl=$('timer'),powerEl=$('power'),startBtn=$('startBtn'),settingsBtn=$('settingsBtn'),settingsMenu=$('settingsMenu'),newGameBtn=$('newGameBtn'),pauseBtn=$('pauseBtn'),resumeBtn=$('resumeBtn'),restartBtn=$('restartBtn'),refreshBtn=$('refreshBtn'),installBtn=$('installBtn'),iosInstallBtn=$('iosInstallBtn'),iosInstallHelp=$('iosInstallHelp'),closeIosInstallHelpBtn=$('closeIosInstallHelpBtn'),closeSettingsBtn=$('closeSettingsBtn'),pauseOverlay=$('pauseOverlay'),resumeFromPauseBtn=$('resumeFromPauseBtn'),restartFromPauseBtn=$('restartFromPauseBtn');
let width,height,centerX,centerY,scale=1,player,enemies,bullets,enemyBullets,particles,powerups,score,lives,gameRunning=false,paused=false,startTime,timerInterval,lastFireTime=0,playerTargetX,playerTargetY,firePower=1,deferredInstallPrompt=null;
function resize(){width=innerWidth;height=innerHeight;canvas.width=width;canvas.height=height;centerX=width/2;centerY=height/2;scale=Math.max(.78,Math.min(1.18,Math.min(width,height)/390))}addEventListener('resize',resize);resize();
const S=n=>n*scale;function elapsed(){return gameRunning?Math.floor((Date.now()-startTime)/1000):0}function level(){return Math.floor(elapsed()/8)}function hit(a,b){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<(a.r+b.r)*(a.r+b.r)}function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push(new Particle(x,y,color))}
class Player{constructor(){this.x=centerX;this.y=height*.8;this.size=S(16)}update(x,y){this.size=S(16);if(x!==undefined){this.x=x;this.y=y}this.x=Math.max(this.size,Math.min(width-this.size,this.x));this.y=Math.max(this.size,Math.min(height-this.size,this.y))}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.beginPath();ctx.moveTo(0,-this.size);ctx.lineTo(-this.size*.72,this.size*.72);ctx.lineTo(this.size*.72,this.size*.72);ctx.closePath();ctx.strokeStyle='#fff';ctx.lineWidth=S(2.5);ctx.stroke();ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size*.68}}}
class Enemy{constructor(){const edge=Math.floor(Math.random()*3);if(edge===0){this.x=Math.random()*width;this.y=-S(28)}else if(edge===1){this.x=width+S(28);this.y=Math.random()*height*.65}else{this.x=-S(28);this.y=Math.random()*height*.65}const a=Math.atan2(height*.58-this.y,centerX-this.x),speed=S(1.35+Math.random()*1.1+level()*.22);this.vx=Math.cos(a)*speed;this.vy=Math.sin(a)*speed;this.size=S(12+Math.random()*9);this.rotation=0;this.rotationSpeed=(Math.random()-.5)*.06;this.shooter=Math.random()<Math.min(.18+level()*.025,.55);this.lastShot=Date.now()+Math.random()*900}update(){this.x+=this.vx;this.y+=this.vy;this.rotation+=this.rotationSpeed;if(this.shooter&&Date.now()-this.lastShot>Math.max(520,1350-level()*55)){enemyBullets.push(new EnemyBullet(this.x,this.y+this.size*.7));this.lastShot=Date.now()}}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rotation);ctx.strokeStyle=this.shooter?'#ff8a3d':'#ff4444';ctx.lineWidth=S(2);ctx.beginPath();ctx.arc(0,0,this.size,0,Math.PI*2);ctx.stroke();if(this.shooter){ctx.beginPath();ctx.moveTo(0,-this.size*.38);ctx.lineTo(0,this.size*.38);ctx.stroke()}ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size}}}
class Powerup{constructor(){this.x=S(28)+Math.random()*(width-S(56));this.y=-S(26);this.size=S(18);this.vy=S(2+level()*.12);this.rotation=0}update(){this.y+=this.vy;this.rotation+=.03}draw(){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.rotation);ctx.strokeStyle='#249bff';ctx.lineWidth=S(3);ctx.strokeRect(-this.size/2,-this.size/2,this.size,this.size);ctx.restore()}b(){return{x:this.x,y:this.y,r:this.size*.72}}}
class Bullet{constructor(x,y,vx=0){this.x=x;this.y=y;this.vx=vx;this.vy=-S(13);this.r=S(3.4);this.life=110}update(){this.x+=this.vx;this.y+=this.vy;this.life--}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()}b(){return{x:this.x,y:this.y,r:this.r}}}
class EnemyBullet{constructor(x,y){this.x=x;this.y=y;this.vx=0;this.vy=S(6.2+level()*.18);this.r=S(4);this.life=180}update(){this.y+=this.vy;this.life--}draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fillStyle='#ff783d';ctx.fill()}b(){return{x:this.x,y:this.y,r:this.r}}}
class Particle{constructor(x,y,color){this.x=x;this.y=y;const a=Math.random()*Math.PI*2,s=S(Math.random()*3.5);this.vx=Math.cos(a)*s;this.vy=Math.sin(a)*s;this.life=1;this.decay=.025+Math.random()*.03;this.color=color;this.r=S(1.5+Math.random()*2.5)}update(){this.x+=this.vx;this.y+=this.vy;this.life-=this.decay}draw(){ctx.globalAlpha=Math.max(0,this.life);ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
function setTarget(e){playerTargetX=e.clientX;playerTargetY=e.clientY}canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||e.pointerType==='pen'){e.preventDefault();setTarget(e)}});canvas.addEventListener('touchstart',e=>e.preventDefault(),{passive:false});canvas.addEventListener('touchmove',e=>e.preventDefault(),{passive:false});
function spawn(){const l=level(),cap=9+l*2;if(enemies.length<cap&&Math.random()<.042+l*.009)enemies.push(new Enemy());if(Math.random()<.0017+Math.min(l,10)*.00025)powerups.push(new Powerup())}function shoot(now){const cd=firePower===2?102:118;if(now-lastFireTime<cd)return;lastFireTime=now;bullets.push(new Bullet(player.x,player.y-player.size));if(firePower===2){bullets.push(new Bullet(player.x-S(7),player.y-player.size,-S(.85)));bullets.push(new Bullet(player.x+S(7),player.y-player.size,S(.85)))}}
function damage(){lives--;livesEl.textContent='Lives: '+lives;burst(player.x,player.y,'#ff783d',14);if(lives<=0)gameOver()}
function collisions(){const pb=player.b();for(let i=powerups.length-1;i>=0;i--){for(let j=bullets.length-1;j>=0;j--){if(hit(powerups[i].b(),bullets[j].b())){const p=powerups[i];powerups.splice(i,1);bullets.splice(j,1);firePower=2;powerEl.textContent='Power: 2';score+=250;scoreEl.textContent='Score: '+score;burst(p.x,p.y,'#249bff',18);break}}}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(hit(pb,e.b())){enemies.splice(i,1);burst(e.x,e.y,'#ff4444',14);damage();continue}for(let j=bullets.length-1;j>=0;j--){if(hit(e.b(),bullets[j].b())){enemies.splice(i,1);bullets.splice(j,1);score+=100;scoreEl.textContent='Score: '+score;burst(e.x,e.y,'#ff4444',12);break}}}for(let i=enemyBullets.length-1;i>=0;i--){if(hit(pb,enemyBullets[i].b())){enemyBullets.splice(i,1);damage()}}}
function updateTimer(){const t=elapsed();timerEl.textContent='Time: '+Math.floor(t/60)+':'+String(t%60).padStart(2,'0')}
function update(){if(paused)return;player.update(playerTargetX,playerTargetY);const now=Date.now();shoot(now);enemies.forEach(x=>x.update());powerups.forEach(x=>x.update());bullets.forEach(x=>x.update());enemyBullets.forEach(x=>x.update());particles.forEach(x=>x.update());enemies=enemies.filter(x=>x.x>-S(90)&&x.x<width+S(90)&&x.y>-S(90)&&x.y<height+S(90));powerups=powerups.filter(x=>x.y<height+S(50));bullets=bullets.filter(x=>x.life>0&&x.y>-S(30));enemyBullets=enemyBullets.filter(x=>x.life>0&&x.y<height+S(30));particles=particles.filter(x=>x.life>0);spawn();collisions()}
function draw(){ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);player.draw();enemies.forEach(x=>x.draw());powerups.forEach(x=>x.draw());bullets.forEach(x=>x.draw());enemyBullets.forEach(x=>x.draw());particles.forEach(x=>x.draw())}function loop(){if(!gameRunning)return;update();draw();requestAnimationFrame(loop)}
function startGame(){player=new Player();enemies=[];bullets=[];enemyBullets=[];particles=[];powerups=[];score=0;lives=3;firePower=1;playerTargetX=undefined;playerTargetY=undefined;scoreEl.textContent='Score: 0';livesEl.textContent='Lives: 3';powerEl.textContent='Power: 1';gameRunning=true;paused=false;startTime=Date.now();lastFireTime=0;clearInterval(timerInterval);timerInterval=setInterval(updateTimer,1000);updateTimer();startBtn.style.display='none';settingsBtn.style.display='block';settingsMenu.classList.add('hidden');pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}function pauseGame(){paused=true;pauseOverlay.classList.remove('hidden');settingsMenu.classList.add('hidden')}function resumeGame(){paused=false;pauseOverlay.classList.add('hidden');requestAnimationFrame(loop)}function gameOver(){gameRunning=false;clearInterval(timerInterval);startBtn.textContent='Restart';startBtn.style.display='block';settingsBtn.style.display='none'}function forceRefresh(){if('caches'in window)caches.keys().then(k=>Promise.all(k.map(x=>caches.delete(x))).then(()=>location.replace(location.pathname+'?update='+Date.now())));else location.replace(location.pathname+'?update='+Date.now())}
settingsBtn.onclick=()=>{settingsMenu.classList.remove('hidden');pauseBtn.classList.toggle('hidden',paused);resumeBtn.classList.toggle('hidden',!paused)};newGameBtn.onclick=startGame;pauseBtn.onclick=pauseGame;resumeBtn.onclick=()=>{settingsMenu.classList.add('hidden');resumeGame()};restartBtn.onclick=startGame;refreshBtn.onclick=forceRefresh;closeSettingsBtn.onclick=()=>settingsMenu.classList.add('hidden');resumeFromPauseBtn.onclick=resumeGame;restartFromPauseBtn.onclick=startGame;startBtn.onclick=startGame;iosInstallBtn.onclick=()=>{settingsMenu.classList.add('hidden');iosInstallHelp.classList.remove('hidden')};closeIosInstallHelpBtn.onclick=()=>iosInstallHelp.classList.add('hidden');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;installBtn.classList.add('hidden')};window.addEventListener('appinstalled',()=>installBtn.classList.add('hidden'));ctx.fillStyle='#000';ctx.fillRect(0,0,width,height);
